net computer \\a-aron-ws80 /del
net computer \\adam-ws22 /del
net computer \\APPDBCUSWS16-01 /del
net computer \\eric-ws14 /del
net computer \\jberries-ws16 /del
net computer \\josh-ws55 /del
net computer \\kevin-ws27 /del
net computer \\matt-laptop /del
net computer \\patrick-laptop /del
net computer \\price-laptop /del
net computer \\sholuv-laptop /del

net user a-aron /del
net user adam /del
net user eric /del
net user justin /del
net user josh /del
net user kevin /del
net user matt /del
net user patrick /del
net user price /del
net user sholuv /del
net user web.user /del
net user kgilstrong-adm /del
